-- CRIAÇÃO DAS TABELAS DE ALUNO(SEM FOTO) E TURMA

CREATE TABLE aluno (
   id BIGSERIAL NOT NULL,
   nome VARCHAR(70) NOT NULL,
   data_nascimento DATE NOT NULL,
   ativo BOOLEAN NOT NULL DEFAULT TRUE,

   PRIMARY KEY(id)
);

CREATE TABLE turma (
   id BIGSERIAL NOT NULL,
   nome_turma VARCHAR(70) NOT NULL,
   turno VARCHAR(10) NOT NULL,
   ano SMALLINT NOT NULL,
   semestre SMALLINT,
   ativo BOOLEAN NOT NULL DEFAULT TRUE,

   PRIMARY KEY(id)
);

-- POR SER UMA RELAÇÃO N PARA MUITOS, GERA UMA TABELA ASSOCIATIVA

CREATE TABLE matricula (
    id BIGSERIAL NOT NULL,
    aluno_id BIGINT NOT NULL,
    turma_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY(id),
    CONSTRAINT fk_aluno_id FOREIGN KEY (aluno_id) REFERENCES aluno (id),
    CONSTRAINT fk_turma FOREIGN KEY (turma_id) REFERENCES turma (id),
    CONSTRAINT uk_matricula UNIQUE (aluno_id, turma_id) -- FAZ COM QUE NÃO TENHA REPETICAO DE UM MESMO ALUNO NA TURMA
);